# Generated by Django 4.1 on 2022-10-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha_pub',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha_pub',
            field=models.CharField(max_length=50),
        ),
    ]
